"""initial schema

Revision ID: 690a516ed7db
Revises: 
Create Date: 2026-06-23 22:03:15.527539+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690a516ed7db'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_email_from_address'), ['from_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_email_to_address'), ['to_address'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('api_key',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_user_id'), ['user_id'], unique=False)

    op.create_table('cf_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_api_token', sa.Text(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('permission_type', sa.String(length=16), nullable=False),
    sa.Column('allowed_zone_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cf_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cf_account_user_id'), ['user_id'], unique=False)

    op.create_table('domain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cf_account_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(length=64), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cf_account_id'], ['cf_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_cf_account_id'), ['cf_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_domain_name'), ['domain_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_zone_id'), ['zone_id'], unique=False)

    op.create_table('domain_assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'user_id', name='uq_domain_user')
    )
    with op.batch_alter_table('domain_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_assignment_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_assignment_user_id'), ['user_id'], unique=False)

    op.create_table('email_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local_part', sa.String(length=128), nullable=False),
    sa.Column('full_address', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_address_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_address_full_address'), ['full_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_address_user_id'), ['user_id'], unique=False)

    op.create_table('forwarding_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_address_id', sa.Integer(), nullable=False),
    sa.Column('destination_email', sa.String(length=320), nullable=False),
    sa.Column('cf_rule_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['email_address_id'], ['email_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forwarding_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forwarding_rule_email_address_id'), ['email_address_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forwarding_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forwarding_rule_email_address_id'))

    op.drop_table('forwarding_rule')
    with op.batch_alter_table('email_address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_address_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_address_full_address'))
        batch_op.drop_index(batch_op.f('ix_email_address_domain_id'))

    op.drop_table('email_address')
    with op.batch_alter_table('domain_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_domain_assignment_domain_id'))

    op.drop_table('domain_assignment')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_zone_id'))
        batch_op.drop_index(batch_op.f('ix_domain_domain_name'))
        batch_op.drop_index(batch_op.f('ix_domain_cf_account_id'))

    op.drop_table('domain')
    with op.batch_alter_table('cf_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cf_account_user_id'))

    op.drop_table('cf_account')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_key_hash'))

    op.drop_table('api_key')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('inbound_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_email_to_address'))
        batch_op.drop_index(batch_op.f('ix_inbound_email_from_address'))

    op.drop_table('inbound_email')
    # ### end Alembic commands ###
